# **Laboratory Task 5**


1. Perform Standard Imports


2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.


3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.


4. Create a tensor "x" from the array above


5. Change the dtype of x from int32 to int64


6. Reshape x into a 3x2 tensor
There are several ways to do this.


7. Return the right-hand column of tensor x


8. Without changing x, return a tensor of square values of x
There are several ways to do this.


9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed.
Think about what shape it should have to permit matrix multiplication.


10. Find the matrix product of x and y.

In [1]:
# Import
import torch
import numpy as np
import sys

In [2]:
# Setting random seed
def set_seed(seed:int):
    np.random.seed(seed)

In [3]:
# create array
set_seed(42)

arr = np.random.randint(0,5,(6))

print(arr)

[3 4 2 4 4 1]


In [4]:
# convert from numpy to tensor
x = torch.from_numpy(arr)
print(x)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


In [5]:
# convert data type
x = x.type(torch.int64)

print('New:', x.type())

New: torch.LongTensor


In [6]:
# 3x2 tensor
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [7]:
# right-hand column
x[:,1]

tensor([1, 3, 5])

In [8]:
# squared of x
x.pow(2)

tensor([[ 0,  1],
        [ 4,  9],
        [16, 25]])

In [9]:
# create tensor object y same as x
y = torch.randint(0, 5, (2, 3))
print(y)

tensor([[2, 4, 0],
        [4, 2, 4]])


In [10]:
# x multiplied by y
x.matmul(y)

tensor([[ 4,  2,  4],
        [16, 14, 12],
        [28, 26, 20]])